"""horarios table

Revision ID: 72ec56c82d25
Revises: 
Create Date: 2019-10-27 04:41:22.166268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ec56c82d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jueves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lunes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maestro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('martes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miercoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sabado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viernes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Entrada', sa.Integer(), nullable=True),
    sa.Column('Salida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario'], ['horario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juevesh',
    sa.Column('horario.id', sa.Integer(), nullable=False),
    sa.Column('jueves.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario.id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['jueves.id'], ['jueves.id'], ),
    sa.PrimaryKeyConstraint('horario.id', 'jueves.id')
    )
    op.create_table('lunesh',
    sa.Column('horario.id', sa.Integer(), nullable=False),
    sa.Column('lunes.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario.id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['lunes.id'], ['lunes.id'], ),
    sa.PrimaryKeyConstraint('horario.id', 'lunes.id')
    )
    op.create_table('martesh',
    sa.Column('horario.id', sa.Integer(), nullable=False),
    sa.Column('martes.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario.id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['martes.id'], ['martes.id'], ),
    sa.PrimaryKeyConstraint('horario.id', 'martes.id')
    )
    op.create_table('materias',
    sa.Column('materias.id', sa.Integer(), nullable=False),
    sa.Column('maestro.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maestro.id'], ['maestro.id'], ),
    sa.ForeignKeyConstraint(['materias.id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('materias.id', 'maestro.id')
    )
    op.create_table('miercolesh',
    sa.Column('horario.id', sa.Integer(), nullable=False),
    sa.Column('miercoles.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario.id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['miercoles.id'], ['miercoles.id'], ),
    sa.PrimaryKeyConstraint('horario.id', 'miercoles.id')
    )
    op.create_table('viernesh',
    sa.Column('horario.id', sa.Integer(), nullable=False),
    sa.Column('viernes.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario.id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['viernes.id'], ['viernes.id'], ),
    sa.PrimaryKeyConstraint('horario.id', 'viernes.id')
    )
    op.create_table('aulasg',
    sa.Column('grupo.id', sa.Integer(), nullable=False),
    sa.Column('aulas.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aulas.id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['grupo.id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('grupo.id', 'aulas.id')
    )
    op.create_table('materiasg',
    sa.Column('grupo.id', sa.Integer(), nullable=False),
    sa.Column('materia.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo.id'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['materia.id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('grupo.id', 'materia.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materiasg')
    op.drop_table('aulasg')
    op.drop_table('viernesh')
    op.drop_table('miercolesh')
    op.drop_table('materias')
    op.drop_table('martesh')
    op.drop_table('lunesh')
    op.drop_table('juevesh')
    op.drop_table('grupo')
    op.drop_table('viernes')
    op.drop_table('sabado')
    op.drop_table('miercoles')
    op.drop_table('materia')
    op.drop_table('martes')
    op.drop_table('maestro')
    op.drop_table('lunes')
    op.drop_table('jueves')
    op.drop_table('horario')
    op.drop_table('aulas')
    # ### end Alembic commands ###
